[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vaultanchor = "Hw3ZetLFTQu1keyVXS7aeDy89AN41RxSfnZZBfii23rh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
